### ISSUE TITLE
Height and weight channel 

### ISSUE THREAD

**Issue by sgarg-prenuvo** [Michedev/DDPMs-Pytorch#1]
Hello, thank you for the code. This code seems to work fine when there is a square image with H=W but in cases where H and W are different, the network confuses H and W channel in the upsampling step of unet (ddpm_pytorch/model/unet_class.py) and throws an error:

  File "/home/DDPMs-Pytorch/ddpm_pytorch/model/unet_class.py", line 119, in forward_unet
    h = torch.cat([h, hs[-i]], dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 62 but got size 72 for tensor number 1 in the list.

62 is Width  and 72 is the height of downsampled image with orig size of 288 x 248. Please let me know if my observation is correct or I made a mistake somewhere. Thanks.

**Comment by Michedev** [comment]
Thank you for your interest, I will test and fix soon

**Comment by Michedev** [comment]
fixed
